# Generated by Django 3.0.6 on 2020-07-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256, verbose_name='Nombre de Vista')),
                ('sql', models.CharField(max_length=1024, verbose_name='Consulta SQL')),
                ('descripcion', models.CharField(max_length=256, verbose_name='Descripcion')),
            ],
        ),
    ]
