# Generated by Django 3.0.6 on 2020-07-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_views', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vista',
            options={'verbose_name': 'Vista de Bases de Datos', 'verbose_name_plural': 'Vistas de Bases de Datos'},
        ),
        migrations.AlterField(
            model_name='vista',
            name='sql',
            field=models.TextField(max_length=1024, verbose_name='Consulta SQL'),
        ),
    ]
