# Generated by Django 3.0.6 on 2020-07-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_views', '0002_auto_20200701_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='vista',
            name='output_ex',
            field=models.CharField(default='', max_length=256, verbose_name='Salida de Vista'),
        ),
    ]
