# Generated by Django 3.0.6 on 2020-07-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_views', '0003_vista_output_ex'),
    ]

    operations = [
        migrations.AddField(
            model_name='vista',
            name='nombre_anterior',
            field=models.CharField(blank=True, editable=False, max_length=256, null=True, verbose_name='Nombre de Vista'),
        ),
        migrations.AlterField(
            model_name='vista',
            name='output_ex',
            field=models.CharField(default='', help_text='Salida de vista actual', max_length=256, verbose_name='Salida de Vista'),
        ),
    ]
