# Generated by Django 3.0.5 on 2020-07-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_views', '0005_auto_20200702_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vista',
            name='sql',
            field=models.TextField(max_length=1280, verbose_name='Consulta SQL'),
        ),
    ]
