# Generated by Django 3.0.5 on 2020-07-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_views', '0006_auto_20200702_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vista',
            name='sql',
            field=models.TextField(max_length=2048, verbose_name='Consulta SQL'),
        ),
    ]
