# Generated by Django 3.0.5 on 2020-07-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_views', '0007_auto_20200702_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vista',
            name='output_ex',
            field=models.CharField(default='', help_text='Salida de vista actual', max_length=2048, verbose_name='Salida de Vista'),
        ),
    ]
