# Generated by Django 3.0.5 on 2020-07-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_views', '0008_auto_20200702_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vista',
            name='descripcion',
            field=models.TextField(max_length=512, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='vista',
            name='nombre',
            field=models.CharField(help_text='Debe ser un nombre sin espacios, sera el que tomara la vista en la BD', max_length=256, verbose_name='Nombre de Vista'),
        ),
        migrations.AlterField(
            model_name='vista',
            name='sql',
            field=models.TextField(help_text='Respetar espacios, maximo de caracteres 2084', max_length=2048, verbose_name='Consulta SQL'),
        ),
    ]
