# Generated by Django 3.0.6 on 2020-07-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_views', '0010_auto_20200730_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vista',
            name='sql',
            field=models.TextField(help_text='Respetar espacios, maximo de caracteres 8000', max_length=8000, verbose_name='Consulta SQL'),
        ),
    ]
