# Generated by Django 3.0.5 on 2020-06-11 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_indicador', models.CharField(default='', max_length=256, verbose_name='Id Indicador')),
                ('dataset_asociado', models.CharField(choices=[('contactosbotitriage', 'contactosbotitriage')], max_length=256, verbose_name='Dataset Asociado')),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_indicador', models.CharField(default='', max_length=256, verbose_name='Id Indicador')),
                ('dataset_asociado', models.CharField(choices=[('contactosbotitriage', 'contactosbotitriage')], max_length=256, verbose_name='Dataset Asociado')),
                ('render', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
            },
        ),
        migrations.CreateModel(
            name='Grafico_barras_y_lineas',
            fields=[
                ('componente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='componentes.Componente')),
                ('label_x', models.CharField(default='', max_length=256, verbose_name='Label Eje X')),
                ('label_y', models.CharField(default='', max_length=256, verbose_name='Label Eje Y')),
                ('color', models.CharField(default='', max_length=256, verbose_name='Color')),
                ('leyenda', models.CharField(default='', max_length=256, verbose_name='Leyenda')),
            ],
            options={
                'abstract': False,
            },
            bases=('componentes.componente',),
        ),
        migrations.CreateModel(
            name='Grafico_de_barras',
            fields=[
                ('componente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='componentes.Componente')),
                ('label_x', models.CharField(default='', max_length=256, verbose_name='Label Eje X')),
                ('label_y', models.CharField(default='', max_length=256, verbose_name='Label Eje Y')),
                ('color', models.CharField(default='', max_length=256, verbose_name='Color')),
                ('leyenda', models.CharField(default='', max_length=256, verbose_name='Leyenda')),
            ],
            options={
                'abstract': False,
            },
            bases=('componentes.componente',),
        ),
        migrations.CreateModel(
            name='Grafico_lineas',
            fields=[
                ('componente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='componentes.Componente')),
                ('label_x', models.CharField(default='', max_length=256, verbose_name='Label Eje X')),
                ('label_y', models.CharField(default='', max_length=256, verbose_name='Label Eje Y')),
                ('color', models.CharField(default='', max_length=256, verbose_name='Color')),
                ('leyenda', models.CharField(default='', max_length=256, verbose_name='Leyenda')),
            ],
            options={
                'abstract': False,
            },
            bases=('componentes.componente',),
        ),
        migrations.CreateModel(
            name='Tarjeta_evolucion_SA',
            fields=[
                ('componente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='componentes.Componente')),
                ('titulo', models.CharField(default='', max_length=256, verbose_name='Titulo')),
                ('subtitulo', models.CharField(blank=True, max_length=256, null=True, verbose_name='Subtitulo')),
                ('muestra', models.IntegerField(default=15, null=True, verbose_name='Periodo')),
                ('link_datos', models.URLField(blank=True, null=True, verbose_name='Link a datos')),
            ],
            options={
                'verbose_name': 'Tarjeta Evolucion sin Agrupacion',
                'verbose_name_plural': 'Tarjetas Evolucion sin Agrupacion',
            },
            bases=('componentes.componente',),
        ),
        migrations.CreateModel(
            name='Tarjeta_evolucion_suma',
            fields=[
                ('componente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='componentes.Componente')),
                ('titulo', models.CharField(default='', max_length=256, verbose_name='Titulo')),
                ('subtitulo', models.CharField(blank=True, max_length=256, null=True, verbose_name='Subtitulo')),
                ('muestra', models.IntegerField(default=15, null=True, verbose_name='Periodo')),
                ('link_datos', models.URLField(blank=True, null=True, verbose_name='Link a datos')),
            ],
            options={
                'verbose_name': 'Tarjeta Evolucion con Suma',
                'verbose_name_plural': 'Tarjetas Evolucion con Suma',
            },
            bases=('componentes.componente',),
        ),
        migrations.CreateModel(
            name='Tarjeta_Porcentaje',
            fields=[
                ('componente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='componentes.Componente')),
                ('titulo', models.CharField(default='', max_length=256, verbose_name='Titulo')),
                ('subtitulo', models.CharField(blank=True, max_length=256, null=True, verbose_name='Subtitulo')),
                ('muestra', models.IntegerField(default=15, null=True, verbose_name='Periodo')),
                ('link_datos', models.URLField(blank=True, null=True, verbose_name='Link a datos')),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'verbose_name_plural': 'Tarjetas',
                'abstract': False,
            },
            bases=('componentes.componente',),
        ),
    ]
