# Generated by Django 3.0.5 on 2020-06-11 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grafico_barras_y_lineas',
            options={'verbose_name_plural': 'Graficos de Barras y Lineas'},
        ),
        migrations.AlterModelOptions(
            name='tarjeta_porcentaje',
            options={'verbose_name_plural': 'Tarjetas Porcentajes'},
        ),
    ]
