# Generated by Django 3.0.5 on 2020-06-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0003_auto_20200611_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='campo_a_observar',
            field=models.CharField(default='', max_length=256, verbose_name='Campo a Observar'),
        ),
        migrations.AddField(
            model_name='componente',
            name='campo_a_ordenar',
            field=models.CharField(default='', max_length=256, verbose_name='Campo a Ordenar'),
        ),
    ]
