# Generated by Django 3.0.5 on 2020-06-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0004_auto_20200611_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta_evolucion_sa',
            name='muestra',
            field=models.FloatField(default=15.0, null=True, verbose_name='Periodo'),
        ),
        migrations.AlterField(
            model_name='tarjeta_evolucion_suma',
            name='muestra',
            field=models.FloatField(default=15.0, null=True, verbose_name='Periodo'),
        ),
        migrations.AlterField(
            model_name='tarjeta_porcentaje',
            name='muestra',
            field=models.FloatField(default=15.0, null=True, verbose_name='Periodo'),
        ),
    ]
