# Generated by Django 3.0.5 on 2020-06-11 18:10

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0006_auto_20200611_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grafico_barras_y_lineas',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AlterField(
            model_name='grafico_de_barras',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AlterField(
            model_name='grafico_lineas',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
