# Generated by Django 3.0.5 on 2020-06-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0008_auto_20200611_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='dataset_asociado',
            field=models.CharField(choices=[('contactosbotitriage', 'contactosbotitriage'), ('casos_sisa', 'casos_sisa')], max_length=256, verbose_name='Dataset Asociado'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='dataset_asociado',
            field=models.CharField(choices=[('contactosbotitriage', 'contactosbotitriage'), ('casos_sisa', 'casos_sisa')], max_length=256, verbose_name='Dataset Asociado'),
        ),
    ]
