# Generated by Django 3.0.6 on 2020-06-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0009_auto_20200611_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='dataset_asociado',
            field=models.CharField(choices=[('dataset', 'dataset'), ('dataset_x_registro', 'dataset_x_registro'), ('dataset_agrupado', 'dataset_agrupado'), ('contactosbotitriage', 'contactosbotitriage'), ('casos_sisa', 'casos_sisa')], max_length=256, verbose_name='Dataset Asociado'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='dataset_asociado',
            field=models.CharField(choices=[('dataset', 'dataset'), ('dataset_x_registro', 'dataset_x_registro'), ('dataset_agrupado', 'dataset_agrupado'), ('contactosbotitriage', 'contactosbotitriage'), ('casos_sisa', 'casos_sisa')], max_length=256, verbose_name='Dataset Asociado'),
        ),
    ]
