# Generated by Django 3.0.6 on 2020-06-12 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0010_auto_20200612_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta_evolucion',
            fields=[
                ('componente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='componentes.Componente')),
                ('titulo', models.CharField(default='', max_length=256, verbose_name='Titulo')),
                ('subtitulo', models.CharField(blank=True, max_length=256, null=True, verbose_name='Subtitulo')),
                ('muestra', models.IntegerField(default=15, null=True, verbose_name='Periodo')),
                ('link_datos', models.URLField(blank=True, null=True, verbose_name='Link a datos')),
                ('funcion_agrupacion', models.CharField(default='', max_length=256, verbose_name='Funcion de Agrupacion')),
            ],
            options={
                'verbose_name': 'Tarjeta Evolucion sin Agrupacion',
                'verbose_name_plural': 'Tarjetas Evolucion sin Agrupacion',
            },
            bases=('componentes.componente',),
        ),
        migrations.AddField(
            model_name='tarjeta_evolucion_suma',
            name='funcion_agrupacion',
            field=models.CharField(default='', max_length=256, verbose_name='Funcion de Agrupacion'),
        ),
        migrations.AddField(
            model_name='tarjeta_porcentaje',
            name='funcion_agrupacion',
            field=models.CharField(default='', max_length=256, verbose_name='Funcion de Agrupacion'),
        ),
        migrations.DeleteModel(
            name='Tarjeta_evolucion_SA',
        ),
    ]
