# Generated by Django 3.0.5 on 2020-06-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0012_auto_20200612_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta_porcentaje',
            name='componente_ptr',
        ),
        migrations.AddField(
            model_name='componente',
            name='campo_fecha',
            field=models.CharField(default='fecha', max_length=256, verbose_name='Nombre columna Fecha'),
        ),
        migrations.AlterField(
            model_name='tarjeta_evolucion',
            name='acumular',
            field=models.BooleanField(default=False, verbose_name='Desea mostrar resultados acumulados? Solo aplica a funciones de suma'),
        ),
        migrations.AlterField(
            model_name='tarjeta_evolucion',
            name='funcion_agrupacion',
            field=models.CharField(choices=[('promedio_por', 'promedio_por'), ('total_por', 'total_por')], default='', max_length=256, verbose_name='Funcion de Agrupacion'),
        ),
        migrations.DeleteModel(
            name='Tarjeta_evolucion_suma',
        ),
        migrations.DeleteModel(
            name='Tarjeta_Porcentaje',
        ),
    ]
