# Generated by Django 3.0.5 on 2020-06-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0013_auto_20200616_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='consulta_personalizada',
            field=models.TextField(blank=True, default='', max_length=600, null=True, verbose_name='Consulta Personalizada'),
        ),
    ]
