# Generated by Django 3.0.5 on 2020-06-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0014_componente_consulta_personalizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='consulta_personalizada',
            field=models.TextField(blank=True, default='cls._meta.model.objects', max_length=600, null=True, verbose_name='Consulta Personalizada'),
        ),
    ]
