# Generated by Django 3.0.5 on 2020-06-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0015_auto_20200616_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componente',
            name='consulta_personalizada',
        ),
        migrations.AddField(
            model_name='componente',
            name='filtros_de_consulta',
            field=models.TextField(blank=True, default='', max_length=600, null=True, verbose_name='Consulta Personalizada'),
        ),
    ]
