# Generated by Django 3.0.6 on 2020-06-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0016_auto_20200616_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta_evolucion',
            name='acumular',
        ),
        migrations.RemoveField(
            model_name='tarjeta_evolucion',
            name='funcion_agrupacion',
        ),
        migrations.AddField(
            model_name='componente',
            name='acumular',
            field=models.BooleanField(default=False, verbose_name='Desea mostrar resultados acumulados? Solo aplica a funciones de suma'),
        ),
        migrations.AddField(
            model_name='componente',
            name='funcion_agrupacion',
            field=models.CharField(choices=[('promedio_por', 'promedio_por'), ('total_por', 'total_por')], default='', max_length=256, verbose_name='Funcion de Agrupacion'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='filtros_de_consulta',
            field=models.TextField(blank=True, default='', max_length=600, null=True, verbose_name='Filtros'),
        ),
    ]
