# Generated by Django 3.0.6 on 2020-06-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0017_auto_20200617_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componente',
            name='funcion_agrupacion',
        ),
        migrations.AddField(
            model_name='grafico_barras_y_lineas',
            name='funcion_agrupacion',
            field=models.CharField(choices=[('total_grafico_historico_por', 'total_grafico_historico_por')], default='', max_length=256, verbose_name='Tipo de Consulta'),
        ),
        migrations.AddField(
            model_name='grafico_de_barras',
            name='funcion_agrupacion',
            field=models.CharField(choices=[('total_grafico_historico_por', 'total_grafico_historico_por')], default='', max_length=256, verbose_name='Tipo de Consulta'),
        ),
        migrations.AddField(
            model_name='grafico_lineas',
            name='funcion_agrupacion',
            field=models.CharField(choices=[('total_grafico_historico_por', 'total_grafico_historico_por')], default='', max_length=256, verbose_name='Tipo de Consulta'),
        ),
        migrations.AddField(
            model_name='tarjeta_evolucion',
            name='funcion_agrupacion',
            field=models.CharField(choices=[('promedio_por', 'promedio_por'), ('total_por', 'total_por')], default='', max_length=256, verbose_name='Tipo de Consulta'),
        ),
    ]
