# Generated by Django 3.0.6 on 2020-06-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0018_auto_20200617_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='acumular',
            field=models.BooleanField(default=False, verbose_name='Desea mostrar resultados acumulados? Solo aplica a funciones de total_por'),
        ),
    ]
