# Generated by Django 3.0.6 on 2020-06-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0019_auto_20200617_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='dataset_asociado',
            field=models.CharField(choices=[('contactosbotitriage', 'contactosbotitriage'), ('casos_sisa', 'casos_sisa')], max_length=256, verbose_name='Dataset Asociado'),
        ),
        migrations.AlterField(
            model_name='grafico_barras_y_lineas',
            name='funcion_agrupacion',
            field=models.CharField(choices=[('total_grafico_historico_por', 'Totalizar por un campo')], default='', max_length=256, verbose_name='Tipo de Consulta'),
        ),
        migrations.AlterField(
            model_name='grafico_de_barras',
            name='funcion_agrupacion',
            field=models.CharField(choices=[('total_grafico_historico_por', 'Totalizar por un campo')], default='', max_length=256, verbose_name='Tipo de Consulta'),
        ),
        migrations.AlterField(
            model_name='grafico_lineas',
            name='funcion_agrupacion',
            field=models.CharField(choices=[('total_grafico_historico_por', 'Totalizar por un campo')], default='', max_length=256, verbose_name='Tipo de Consulta'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='dataset_asociado',
            field=models.CharField(choices=[('contactosbotitriage', 'contactosbotitriage'), ('casos_sisa', 'casos_sisa')], max_length=256, verbose_name='Dataset Asociado'),
        ),
        migrations.AlterField(
            model_name='tarjeta_evolucion',
            name='funcion_agrupacion',
            field=models.CharField(choices=[('total_por', 'Totalizar por un campo'), ('promedio_por', 'Promediar por un campo')], default='', max_length=256, verbose_name='Tipo de Consulta'),
        ),
    ]
