# Generated by Django 3.0.6 on 2020-06-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0020_auto_20200617_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='dataset_asociado',
            field=models.CharField(choices=[('contactosbotitriage', 'contactosbotitriage'), ('casos_sisa', 'casos_sisa'), ('consultas_sisa_por_rango_etario', 'consultas_sisa_por_rango_etario')], max_length=256, verbose_name='Dataset Asociado'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='dataset_asociado',
            field=models.CharField(choices=[('contactosbotitriage', 'contactosbotitriage'), ('casos_sisa', 'casos_sisa'), ('consultas_sisa_por_rango_etario', 'consultas_sisa_por_rango_etario')], max_length=256, verbose_name='Dataset Asociado'),
        ),
    ]
