# Generated by Django 3.0.6 on 2020-06-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0021_auto_20200617_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componente',
            name='acumular',
        ),
        migrations.RemoveField(
            model_name='componente',
            name='campo_a_observar',
        ),
        migrations.RemoveField(
            model_name='componente',
            name='campo_a_ordenar',
        ),
        migrations.RemoveField(
            model_name='componente',
            name='campo_fecha',
        ),
        migrations.AlterField(
            model_name='tarjeta_evolucion',
            name='muestra',
            field=models.IntegerField(default=15, null=True, verbose_name='Muestra'),
        ),
    ]
