# Generated by Django 3.0.6 on 2020-06-18 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0022_auto_20200618_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta_evolucion',
            name='funcion_agrupacion',
        ),
    ]
