# Generated by Django 3.0.6 on 2020-06-18 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0023_remove_tarjeta_evolucion_funcion_agrupacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grafico_barras_y_lineas',
            name='funcion_agrupacion',
        ),
        migrations.RemoveField(
            model_name='grafico_de_barras',
            name='funcion_agrupacion',
        ),
        migrations.RemoveField(
            model_name='grafico_lineas',
            name='funcion_agrupacion',
        ),
    ]
