# Generated by Django 3.0.6 on 2020-06-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0025_auto_20200618_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='dataset_asociado',
            field=models.CharField(choices=[('sisa_consultas_por_rango_etario', 'sisa_consultas_por_rango_etario'), ('botitriage_contactos_evolucion', 'botitriage_contactos_evolucion')], max_length=256, verbose_name='Dataset Asociado'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='dataset_asociado',
            field=models.CharField(choices=[('sisa_consultas_por_rango_etario', 'sisa_consultas_por_rango_etario'), ('botitriage_contactos_evolucion', 'botitriage_contactos_evolucion')], max_length=256, verbose_name='Dataset Asociado'),
        ),
    ]
