# Generated by Django 3.0.6 on 2020-06-18 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0026_auto_20200618_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grafico_de_barras',
            options={'verbose_name_plural': 'Graficos'},
        ),
    ]
