# Generated by Django 3.0.6 on 2020-06-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0027_auto_20200618_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta_evolucion',
            name='grafico',
            field=models.BooleanField(default=True, verbose_name='Mostrar Grafico'),
        ),
    ]
