# Generated by Django 3.0.6 on 2020-06-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0028_tarjeta_evolucion_grafico'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta_evolucion',
            name='acumular',
            field=models.BooleanField(default=False, verbose_name='Mostrar datos acumulados'),
        ),
    ]
