# Generated by Django 3.0.5 on 2020-06-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0029_tarjeta_evolucion_acumular'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='campo_fecha',
            field=models.CharField(blank=True, default='fecha', max_length=256, null=True, verbose_name='Campo Fecha'),
        ),
    ]
