# Generated by Django 3.0.5 on 2020-06-19 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0030_componente_campo_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componente',
            name='campo_fecha',
        ),
    ]
