# Generated by Django 3.0.5 on 2020-06-19 18:00

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0034_auto_20200619_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grafico_cartesiano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_indicador', models.CharField(default='', max_length=256, verbose_name='Id Indicador')),
                ('dataset_asociado', models.CharField(choices=[('sisa_consultas_por_rango_etario', 'sisa_consultas_por_rango_etario'), ('botitriage_contactos_evolucion', 'botitriage_contactos_evolucion'), ('botitriage_contactos_acumulado', 'botitriage_contactos_acumulado')], max_length=256, verbose_name='Dataset Asociado')),
                ('filtros_de_consulta', models.TextField(blank=True, default='', max_length=600, null=True, verbose_name='Filtros')),
                ('label_x', models.CharField(default='', max_length=256, verbose_name='Label Eje X')),
                ('label_y', models.CharField(default='', max_length=256, verbose_name='Label Eje Y')),
                ('color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('leyenda', models.CharField(default='', max_length=256, verbose_name='Leyenda')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_indicador', models.CharField(default='', max_length=256, verbose_name='Id Indicador')),
                ('dataset_asociado', models.CharField(choices=[('sisa_consultas_por_rango_etario', 'sisa_consultas_por_rango_etario'), ('botitriage_contactos_evolucion', 'botitriage_contactos_evolucion'), ('botitriage_contactos_acumulado', 'botitriage_contactos_acumulado')], max_length=256, verbose_name='Dataset Asociado')),
                ('filtros_de_consulta', models.TextField(blank=True, default='', max_length=600, null=True, verbose_name='Filtros')),
                ('titulo', models.CharField(default='', max_length=256, verbose_name='Titulo')),
                ('subtitulo', models.CharField(blank=True, max_length=256, null=True, verbose_name='Subtitulo')),
                ('muestra', models.IntegerField(default=15, null=True, verbose_name='Muestra')),
                ('link_datos', models.URLField(blank=True, null=True, verbose_name='Link a datos')),
                ('grafico', models.BooleanField(default=True, verbose_name='Mostrar Grafico')),
                ('acumular', models.BooleanField(default=False, verbose_name='Mostrar datos acumulados')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='grafico_barras_y_lineas',
            name='componente_ptr',
        ),
        migrations.RemoveField(
            model_name='grafico_de_barras',
            name='componente_ptr',
        ),
        migrations.RemoveField(
            model_name='grafico_lineas',
            name='componente_ptr',
        ),
        migrations.RemoveField(
            model_name='tarjeta_evolucion',
            name='componente_ptr',
        ),
        migrations.DeleteModel(
            name='Componente',
        ),
        migrations.DeleteModel(
            name='Grafico_barras_y_lineas',
        ),
        migrations.DeleteModel(
            name='Grafico_de_barras',
        ),
        migrations.DeleteModel(
            name='Grafico_lineas',
        ),
        migrations.DeleteModel(
            name='Tarjeta_evolucion',
        ),
    ]
