# Generated by Django 3.0.5 on 2020-06-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0035_auto_20200619_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='grafico_cartesiano',
            name='tipo_grafico',
            field=models.CharField(default='', max_length=256, verbose_name='Tipo de Grafico'),
        ),
    ]
