# Generated by Django 3.0.5 on 2020-06-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0036_grafico_cartesiano_tipo_grafico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grafico_cartesiano',
            name='dataset_asociado',
            field=models.CharField(choices=[('sisa_confirmados_por_rango_etario', 'sisa_confirmados_por_rango_etario'), ('sisa_total_por_rango_etario', 'sisa_total_por_rango_etario'), ('botitriage_contactos_evolucion', 'botitriage_contactos_evolucion'), ('botitriage_contactos_acumulado', 'botitriage_contactos_acumulado')], max_length=256, verbose_name='Dataset Asociado'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='dataset_asociado',
            field=models.CharField(choices=[('sisa_confirmados_por_rango_etario', 'sisa_confirmados_por_rango_etario'), ('sisa_total_por_rango_etario', 'sisa_total_por_rango_etario'), ('botitriage_contactos_evolucion', 'botitriage_contactos_evolucion'), ('botitriage_contactos_acumulado', 'botitriage_contactos_acumulado')], max_length=256, verbose_name='Dataset Asociado'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='dataset_asociado',
            field=models.CharField(choices=[('sisa_confirmados_por_rango_etario', 'sisa_confirmados_por_rango_etario'), ('sisa_total_por_rango_etario', 'sisa_total_por_rango_etario'), ('botitriage_contactos_evolucion', 'botitriage_contactos_evolucion'), ('botitriage_contactos_acumulado', 'botitriage_contactos_acumulado')], max_length=256, verbose_name='Dataset Asociado'),
        ),
    ]
