# Generated by Django 3.0.5 on 2020-06-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0038_auto_20200622_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grafico_cartesiano',
            name='dataset_asociado',
            field=models.CharField(choices=[('sisa_confirmados_por_rango_etario', 'sisa_confirmados_por_rango_etario'), ('sisa_total_por_rango_etario', 'sisa_total_por_rango_etario'), ('botitriage_contactos_evolucion', 'botitriage_contactos_evolucion'), ('botitriage_contactos_acumulado', 'botitriage_contactos_acumulado'), ('porcentaje_test', 'porcentaje_test'), ('sisa_letalidad_por_rango_etario', 'sisa_letalidad_por_rango_etario')], max_length=256, verbose_name='Dataset Asociado'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='dataset_asociado',
            field=models.CharField(choices=[('sisa_confirmados_por_rango_etario', 'sisa_confirmados_por_rango_etario'), ('sisa_total_por_rango_etario', 'sisa_total_por_rango_etario'), ('botitriage_contactos_evolucion', 'botitriage_contactos_evolucion'), ('botitriage_contactos_acumulado', 'botitriage_contactos_acumulado'), ('porcentaje_test', 'porcentaje_test'), ('sisa_letalidad_por_rango_etario', 'sisa_letalidad_por_rango_etario')], max_length=256, verbose_name='Dataset Asociado'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='dataset_asociado',
            field=models.CharField(choices=[('sisa_confirmados_por_rango_etario', 'sisa_confirmados_por_rango_etario'), ('sisa_total_por_rango_etario', 'sisa_total_por_rango_etario'), ('botitriage_contactos_evolucion', 'botitriage_contactos_evolucion'), ('botitriage_contactos_acumulado', 'botitriage_contactos_acumulado'), ('porcentaje_test', 'porcentaje_test'), ('sisa_letalidad_por_rango_etario', 'sisa_letalidad_por_rango_etario')], max_length=256, verbose_name='Dataset Asociado'),
        ),
    ]
