# Generated by Django 3.0.5 on 2020-06-22 18:53

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0039_auto_20200622_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grafico_cartesiano',
            name='color',
        ),
        migrations.AddField(
            model_name='grafico_cartesiano',
            name='color1',
            field=colorfield.fields.ColorField(default='#fdd306', max_length=18),
        ),
        migrations.AddField(
            model_name='grafico_cartesiano',
            name='color2',
            field=colorfield.fields.ColorField(default='#037dbf', max_length=18),
        ),
        migrations.AddField(
            model_name='grafico_cartesiano',
            name='color3',
            field=colorfield.fields.ColorField(default='#e74c3c', max_length=18),
        ),
    ]
