# Generated by Django 3.0.5 on 2020-06-22 19:05

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0040_auto_20200622_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grafico_cartesiano',
            name='leyenda',
        ),
        migrations.AddField(
            model_name='grafico_cartesiano',
            name='leyendas',
            field=models.CharField(default='', help_text='Acepta las leyendas separas por coma, tiene sentido en graficos de varias series', max_length=256, verbose_name='Leyenda'),
        ),
        migrations.AlterField(
            model_name='grafico_cartesiano',
            name='color1',
            field=colorfield.fields.ColorField(default='#fdd306', help_text='Se muestra debajo de todo', max_length=18),
        ),
        migrations.AlterField(
            model_name='grafico_cartesiano',
            name='color2',
            field=colorfield.fields.ColorField(default='#037dbf', help_text='Se muestra en el medio', max_length=18),
        ),
        migrations.AlterField(
            model_name='grafico_cartesiano',
            name='color3',
            field=colorfield.fields.ColorField(default='#e74c3c', help_text='Se muestra por encima de todo', max_length=18),
        ),
        migrations.AlterField(
            model_name='grafico_cartesiano',
            name='tipo_grafico',
            field=models.CharField(default='', help_text='Acepta line, bar, doughnut separadas por coma. Ej: line,bar (grafico de linea y barras)', max_length=256, verbose_name='Tipo de Grafico'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='acumular',
            field=models.BooleanField(default=False, help_text='Si se desea mostrar la serie de datos acumulados.', verbose_name='Mostrar datos acumulados'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='grafico',
            field=models.BooleanField(default=True, help_text='Si se desea mostrar el grafico de tendencia. No aplica para datos unicos', verbose_name='Mostrar Grafico'),
        ),
    ]
