# Generated by Django 3.0.6 on 2020-06-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0051_auto_20200623_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_indicador', models.CharField(default='', max_length=256, verbose_name='Id Indicador')),
                ('dataset_asociado', models.CharField(choices=[('sisa_letalidad_por_rango_etario', 'sisa_letalidad_por_rango_etario'), ('sisa_confirmados_por_rango_etario', 'sisa_confirmados_por_rango_etario'), ('sisa_positivos_por_dia', 'sisa_positivos_por_dia'), ('sisa_total_por_rango_etario', 'sisa_total_por_rango_etario'), ('sisa_positivos_alta_dia', 'sisa_positivos_alta_dia'), ('sisa_fallecidos_dia', 'sisa_fallecidos_dia'), ('sisa_hisopados_confirmados_dia', 'sisa_hisopados_confirmados_dia'), ('sisa_positivos_genero', 'sisa_positivos_genero'), ('sisa_fallecidos_promedio', 'sisa_fallecidos_promedio'), ('sisa_letalidad', 'sisa_letalidad'), ('sisa_positivos_acumulado', 'sisa_positivos_acumulado'), ('sisa_altas_acumulado', 'sisa_altas_acumulado'), ('sisa_fallecidos_acumulado', 'sisa_fallecidos_acumulado'), ('botitriage_contactos_evolucion', 'botitriage_contactos_evolucion'), ('botitriage_contactos_acumulado', 'botitriage_contactos_acumulado'), ('porcentaje_test', 'porcentaje_test')], max_length=256, verbose_name='Dataset Asociado')),
                ('filtros_de_consulta', models.TextField(blank=True, default='', max_length=600, null=True, verbose_name='Filtros')),
                ('leyendas', models.CharField(default='', help_text='Acepta las leyendas separas por coma, tiene sentido en graficos de varias series', max_length=256, verbose_name='Leyenda')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='grafico_cartesiano',
            name='dataset_asociado',
            field=models.CharField(choices=[('sisa_letalidad_por_rango_etario', 'sisa_letalidad_por_rango_etario'), ('sisa_confirmados_por_rango_etario', 'sisa_confirmados_por_rango_etario'), ('sisa_positivos_por_dia', 'sisa_positivos_por_dia'), ('sisa_total_por_rango_etario', 'sisa_total_por_rango_etario'), ('sisa_positivos_alta_dia', 'sisa_positivos_alta_dia'), ('sisa_fallecidos_dia', 'sisa_fallecidos_dia'), ('sisa_hisopados_confirmados_dia', 'sisa_hisopados_confirmados_dia'), ('sisa_positivos_genero', 'sisa_positivos_genero'), ('sisa_fallecidos_promedio', 'sisa_fallecidos_promedio'), ('sisa_letalidad', 'sisa_letalidad'), ('sisa_positivos_acumulado', 'sisa_positivos_acumulado'), ('sisa_altas_acumulado', 'sisa_altas_acumulado'), ('sisa_fallecidos_acumulado', 'sisa_fallecidos_acumulado'), ('botitriage_contactos_evolucion', 'botitriage_contactos_evolucion'), ('botitriage_contactos_acumulado', 'botitriage_contactos_acumulado'), ('porcentaje_test', 'porcentaje_test')], max_length=256, verbose_name='Dataset Asociado'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='dataset_asociado',
            field=models.CharField(choices=[('sisa_letalidad_por_rango_etario', 'sisa_letalidad_por_rango_etario'), ('sisa_confirmados_por_rango_etario', 'sisa_confirmados_por_rango_etario'), ('sisa_positivos_por_dia', 'sisa_positivos_por_dia'), ('sisa_total_por_rango_etario', 'sisa_total_por_rango_etario'), ('sisa_positivos_alta_dia', 'sisa_positivos_alta_dia'), ('sisa_fallecidos_dia', 'sisa_fallecidos_dia'), ('sisa_hisopados_confirmados_dia', 'sisa_hisopados_confirmados_dia'), ('sisa_positivos_genero', 'sisa_positivos_genero'), ('sisa_fallecidos_promedio', 'sisa_fallecidos_promedio'), ('sisa_letalidad', 'sisa_letalidad'), ('sisa_positivos_acumulado', 'sisa_positivos_acumulado'), ('sisa_altas_acumulado', 'sisa_altas_acumulado'), ('sisa_fallecidos_acumulado', 'sisa_fallecidos_acumulado'), ('botitriage_contactos_evolucion', 'botitriage_contactos_evolucion'), ('botitriage_contactos_acumulado', 'botitriage_contactos_acumulado'), ('porcentaje_test', 'porcentaje_test')], max_length=256, verbose_name='Dataset Asociado'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='dataset_asociado',
            field=models.CharField(choices=[('sisa_letalidad_por_rango_etario', 'sisa_letalidad_por_rango_etario'), ('sisa_confirmados_por_rango_etario', 'sisa_confirmados_por_rango_etario'), ('sisa_positivos_por_dia', 'sisa_positivos_por_dia'), ('sisa_total_por_rango_etario', 'sisa_total_por_rango_etario'), ('sisa_positivos_alta_dia', 'sisa_positivos_alta_dia'), ('sisa_fallecidos_dia', 'sisa_fallecidos_dia'), ('sisa_hisopados_confirmados_dia', 'sisa_hisopados_confirmados_dia'), ('sisa_positivos_genero', 'sisa_positivos_genero'), ('sisa_fallecidos_promedio', 'sisa_fallecidos_promedio'), ('sisa_letalidad', 'sisa_letalidad'), ('sisa_positivos_acumulado', 'sisa_positivos_acumulado'), ('sisa_altas_acumulado', 'sisa_altas_acumulado'), ('sisa_fallecidos_acumulado', 'sisa_fallecidos_acumulado'), ('botitriage_contactos_evolucion', 'botitriage_contactos_evolucion'), ('botitriage_contactos_acumulado', 'botitriage_contactos_acumulado'), ('porcentaje_test', 'porcentaje_test')], max_length=256, verbose_name='Dataset Asociado'),
        ),
    ]
