# Generated by Django 3.0.5 on 2020-06-24 15:00

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0061_tarjeta_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='color',
            field=colorfield.fields.ColorField(default='#ffc107', help_text='Color de Tarjeta', max_length=18),
        ),
    ]
