# Generated by Django 3.0.5 on 2020-06-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0066_auto_20200624_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='comentarios',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Comentarios'),
        ),
    ]
