# Generated by Django 3.0.5 on 2020-06-26 14:14

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0073_auto_20200625_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='grafico_cartesiano',
            name='cant_distinto_color',
            field=models.IntegerField(blank=True, help_text='Se mostraran en otro color, segun lo indicado en el campo color_columnas_revision', null=True, verbose_name='Cantidad de columnas en revision'),
        ),
        migrations.AddField(
            model_name='grafico_cartesiano',
            name='color_columnas_revision',
            field=colorfield.fields.ColorField(default='#717170', max_length=18, verbose_name='Color Columnas Revision'),
        ),
        migrations.AlterField(
            model_name='grafico_cartesiano',
            name='tipo_grafico',
            field=models.CharField(default='', help_text='Acepta line, bar separadas por coma. Ej: line,bar (grafico de linea y barras)', max_length=256, verbose_name='Tipo de Grafico'),
        ),
    ]
