# Generated by Django 3.0.5 on 2020-06-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0074_auto_20200626_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='id_componente',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
