# Generated by Django 3.0.5 on 2020-06-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0075_indicador_id_componente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicador',
            old_name='id_componente',
            new_name='id_indicador_anterior',
        ),
        migrations.AddField(
            model_name='dona',
            name='id_indicador_bk',
            field=models.CharField(default='', max_length=256, verbose_name='Id Indicador Bk'),
        ),
        migrations.AddField(
            model_name='grafico_cartesiano',
            name='id_indicador_bk',
            field=models.CharField(default='', max_length=256, verbose_name='Id Indicador Bk'),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='id_indicador_bk',
            field=models.CharField(default='', max_length=256, verbose_name='Id Indicador Bk'),
        ),
    ]
