# Generated by Django 3.0.5 on 2020-06-26 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0076_auto_20200626_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicador',
            name='id_indicador_anterior',
        ),
    ]
