# Generated by Django 3.0.5 on 2020-06-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0078_auto_20200626_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dona',
            name='id_indicador_bk',
            field=models.CharField(default='', editable=False, max_length=256, verbose_name='Id Indicador Bk'),
        ),
        migrations.AlterField(
            model_name='grafico_cartesiano',
            name='id_indicador_bk',
            field=models.CharField(default='', editable=False, max_length=256, verbose_name='Id Indicador Bk'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='id_indicador_bk',
            field=models.CharField(default='', editable=False, max_length=256, verbose_name='Id Indicador Bk'),
        ),
    ]
