# Generated by Django 3.0.5 on 2020-07-02 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_views', '0004_auto_20200701_1905'),
        ('componentes', '0088_auto_20200702_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dona',
            name='dataset_asociado',
        ),
        migrations.RemoveField(
            model_name='dona',
            name='filtros_de_consulta',
        ),
        migrations.RemoveField(
            model_name='grafico_cartesiano',
            name='dataset_asociado',
        ),
        migrations.RemoveField(
            model_name='grafico_cartesiano',
            name='filtros_de_consulta',
        ),
        migrations.RemoveField(
            model_name='tarjeta',
            name='dataset_asociado',
        ),
        migrations.RemoveField(
            model_name='tarjeta',
            name='filtros_de_consulta',
        ),
        migrations.AddField(
            model_name='dona',
            name='comentarios',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Comentarios'),
        ),
        migrations.AddField(
            model_name='grafico_cartesiano',
            name='comentarios',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='dona',
            name='view_asociada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_views.Vista', verbose_name='Vista Asociada'),
        ),
        migrations.AlterField(
            model_name='grafico_cartesiano',
            name='view_asociada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_views.Vista', verbose_name='Vista Asociada'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='comentarios',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='view_asociada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_views.Vista', verbose_name='Vista Asociada'),
        ),
    ]
