# Generated by Django 3.0.6 on 2020-07-21 13:51

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_views', '0009_auto_20200702_1944'),
        ('componentes', '0089_auto_20200702_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta_doble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_indicador', models.CharField(default='', max_length=256, verbose_name='Id Indicador')),
                ('id_indicador_bk', models.CharField(default='', editable=False, max_length=256, verbose_name='Id Indicador Bk')),
                ('comentarios', models.TextField(blank=True, max_length=256, null=True, verbose_name='Comentarios')),
                ('titulo', models.CharField(default='', max_length=256, verbose_name='Titulo')),
                ('subtitulo1', models.CharField(blank=True, max_length=256, null=True, verbose_name='Subtitulo1')),
                ('subtitulo2', models.CharField(blank=True, max_length=256, null=True, verbose_name='Subtitulo2')),
                ('color', colorfield.fields.ColorField(default='#ffc107', help_text='Color de Tarjeta', max_length=18)),
                ('link_datos', models.URLField(blank=True, null=True, verbose_name='Link a datos')),
                ('view_asociada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_views.Vista', verbose_name='Vista Asociada')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
