# Generated by Django 3.0.6 on 2020-07-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0090_tarjeta_doble'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarjeta_doble',
            options={'verbose_name': 'Indicador', 'verbose_name_plural': 'Indicadores'},
        ),
        migrations.AlterField(
            model_name='tarjeta_doble',
            name='subtitulo1',
            field=models.CharField(help_text='Subtitulo del primer dato', max_length=256, verbose_name='Subtitulo1'),
        ),
        migrations.AlterField(
            model_name='tarjeta_doble',
            name='subtitulo2',
            field=models.CharField(help_text='Subtitulo del segundo dato', max_length=256, verbose_name='Subtitulo2'),
        ),
    ]
