# Generated by Django 3.0.6 on 2020-07-21 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0091_auto_20200721_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarjeta_doble',
            options={'verbose_name': 'Tarjeta Doble', 'verbose_name_plural': 'Tarjetas Dobles'},
        ),
    ]
