# Generated by Django 3.0.6 on 2020-07-21 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0092_auto_20200721_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dona',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='grafico_cartesiano',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='tarjeta_doble',
            name='comentarios',
        ),
    ]
